stiker_one= {
    0: 'CAACAgIAAxkBAAIKhWMiubuUZbn9XIbStaqy1XEcgx4fAAIeHgACneoBSRwM1oK4qKgdKQQ',
    1: 'CAACAgIAAxkBAAIKi2MiueFtaT3JwZmb2yWE_zmMqqeYAAKKHwACRI_5SH-WhXeSCiGQKQQ',
    2: 'CAACAgIAAxkBAAIKkWMiueX8F7dk0QYxVOkugaVBF4dcAAKqHAAC8Rv4SK0mkjG8iMh7KQQ',
    3: 'CAACAgIAAxkBAAIKl2Miuerzvl78z3G3Nl_6J9aZzjaiAAKpHQACO0sBSS3hnz1nLBGCKQQ',
    4: 'CAACAgIAAxkBAAIKnWMiue5o4O9ZhCLwCmjJihWO4ZbOAAImIQAC7OD4SM1n7Jp_VNf7KQQ',
    5: 'CAACAgIAAxkBAAIKo2MiufXB_LS--2ZHZvkQI7ioSSEdAALjHAACJxX4SKb1s3EU1L1-KQQ',
    6: 'CAACAgIAAxkBAAIKqWMiufoNRvMG-DEQXCLonDXI1ChHAALYHQACKEb5SKcWaF2nFZR_KQQ',
    7: 'CAACAgIAAxkBAAIKr2Miuf3x2OYR49iRo0RKQ0e_5_UjAAJ5JgACuBX5SJXye-W57MisKQQ',
    8: 'CAACAgIAAxkBAAIKtWMiugGdezglE7hQt4cHWWKtgeGSAALDHQACbo35SAyAEIkerj4ZKQQ',
    9: 'CAACAgIAAxkBAAIKu2MiugZwCZd9eXcg_fs6-jl__7Z5AAKVHgACEJMBSc3STz6R5BROKQQ'
}

stiker_two= {
    0: 'CAACAgIAAxkBAAIKh2Miuddgb-y_eVPCxuo6E8-tMyjOAAJVHQACIEUAAUlrRdy3ahEU7ykE',
    1: 'CAACAgIAAxkBAAIKjWMiuePOZEskLTFWWQMIAAFKFY5xFgACTh4AAorc-Uj07A-cWrvmuykE',
    2: 'CAACAgIAAxkBAAIKk2Miued0q_rj7vfVNnptpPu0V6LhAAJvIgACAuf4SIL_6x-qAAGFWykE',
    3: 'CAACAgIAAxkBAAIKmWMiuepgFL1V7ozhkhWg0o8vmC7EAALIHQACNaz5SAQiVt6UTAwqKQQ',
    4: 'CAACAgIAAxkBAAIKn2Miue_kV4Nxvu--9z0JpbSMfa7SAAKWIAACVED4SIgJomgdKtt4KQQ',
    5: 'CAACAgIAAxkBAAIKpWMiufbyI79AFjwq1uq4QrJYj0htAAJpHwACkUj5SLdoYOfDC2S2KQQ',
    6: 'CAACAgIAAxkBAAIKq2MiufuDA0SI2AKwAAHzp-aQLLsvxAACTRwAAsAB-UgbYWnsS4y39ikE',
    7: 'CAACAgIAAxkBAAIKsWMiuf3zYC-A6YBWa-TNhB1_-M3rAAINHwACUm_5SA-Q2kehWjl1KQQ',
    8: 'CAACAgIAAxkBAAIKt2MiugJVR-w0opihegyBjbPN34JwAAIKIwACJR74SOyps3Q1AQZDKQQ',
    9: 'CAACAgIAAxkBAAIKvWMiugZnUBT8oN0HP5p1pbmX-6gBAAK-GwACf0X5SFN3js2UyTtEKQQ'
}

stiker_three= {
    0: 'CAACAgIAAxkBAAIKiWMiud0IgSL53DTu-ChMrzoalPQKAAJAHgACNBP4SC1dSJ8f-dQrKQQ',
    1: 'CAACAgIAAxkBAAIKj2MiueSt-T9QUyqf-bcIobdl3Sb8AAJOIAACzEn5SE8wVGHUA2DWKQQ',
    2: 'CAACAgIAAxkBAAIKlWMiuehspBHk7lCOue54GMnQDCJ9AAJSIQACsYT5SOLzo9uPcMHiKQQ',
    3: 'CAACAgIAAxkBAAIKm2Miuet4iq8kWPDxZX6D4nH3ZgYvAALKIAACPpUAAUlMQbQktZAeXSkE',
    4: 'CAACAgIAAxkBAAIKoWMiufGJuBvdxpCYMvBQfscsoNs8AALEHwACyiYBSXA_hhzWmnj5KQQ',
    5: 'CAACAgIAAxkBAAIKp2MiufaYEaBrTbG61o2d7beRU6QeAAJPHgACSIL5SF_yeHf0hgh1KQQ',
    6: 'CAACAgIAAxkBAAIKrWMiufzyLN_Zu45bWrgzRXlxX_GWAAKkHwACdtv4SL-irPxmQsMDKQQ',
    7: 'CAACAgIAAxkBAAIKs2Miuf5CPWBzyZt_IqhT9voAAYQG0AACCB4AAo5Q-Ug60_UGvF1yzykE',
    8: 'CAACAgIAAxkBAAIKuWMiugLaOSV5ZvlY9ecJ12ua5uaDAAJZIAACDjT4SKMCqrqvxCp0KQQ',
    9: ''
}